server:
  port: 9000

spring:
  application:
    name: sc-gateway 
  
  cloud:
    gateway:
      routes:
        - id: hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8761 # 타겟 서비스의 URI
          predicates:
            - Path=/hello # 매칭할 경로 (정확히 /hello)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
